from lib.helper import get_test_folder
from datetime import datetime
import yaml
import os

_config_path = os.path.join(get_test_folder(), 'config.yaml')
with open(_config_path, 'r') as yaml_file:
    now = datetime.now()
    time_stamp = str(datetime.timestamp(now))
    config = yaml.load(yaml_file)
    config['timestamp'] = time_stamp

with open(_config_path, 'w') as yaml_file:
    yaml_file.write(yaml.dump(config, default_flow_style=False))


connect_params = [
    {"name": "data-enrichment-latin1-sup",
     "splunk_hec_json_event_enrichment": "test=supplement,chars=¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿ"
     },
    {"name": "data-enrichment-latin1-A",
     "splunk_hec_json_event_enrichment": "test=extendedA,chars=ĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžſ"
     },
    {"name": "data-enrichment-latin1-B",
     "splunk_hec_json_event_enrichment": "test=extendedB,chars=ƀƁƂƃƄƅƆƇƈƉƊƋƌƍƎƏƐƑƒƓƔƕƖƗƘƙƚƛƜƝƞƟƠơƢƣƤƥƦƧƨƩƪƫƬƭƮƯưƱƲƳƴƵƶƷƸƹƺƻƼƽƾƿǀǁǂǃǄǅǆǇǈǉǊǋǌǍǎǏǐǑǒǓǔǕǖǗǘǙǚǛǜǝǞǟǠǡǢǣǤǥǦǧǨǩǪǫǬǭǮǯǰǱǲǳǴǵǶǷǸǹǺǻǼǽǾǿȀȁȂȃȄȅȆȇȈȉȊȋȌȍȎȏȐȑȒȓȔȕȖȗȘșȚțȜȝȞȟȠȡȢȣȤȥȦȧȨȩȪȫȬȭȮȯȰȱȲȳȴȵȶȷȸȹȺȻȼȽȾȿɀɁɂɃɄɅɆɇɈɉɊɋɌɍɎɏ"
     },
    {"name": "data-enrichment-latin1-spaceModifier",
     "splunk_hec_json_event_enrichment": "test=spaceModifier,chars=ʰʱʲʳʴʵʶʷʸʹʺʻʼʽʾʿˀˁ˂˃˄˅ˆˇˈˉˊˋˌˍˎˏːˑ˒˓˔˕˖˗˘˙˚˛˜˝˞˟ˠˡˢˣˤ˥˦˧˨˩˪˫ˬ˭ˮ˯˰˱˲˳˴˵˶˷˸˹˺˻˼˽˾˿"
     },
    {"name": "data-enrichment-latin1-IPA",
     "splunk_hec_json_event_enrichment": "test=IPAextensions,chars=ɐɑɒɓɔɕɖɗɘəɚɛɜɝɞɟɠɡɢɣɤɥɦɧɨɩɪɫɬɭɮɯɰɱɲɳɴɵɶɷɸɹɺɻɼɽɾɿʀʁʂʃʄʅʆʇʈʉʊʋʌʍʎʏʐʑʒʓʔʕʖʗʘʙʚʛʜʝʞʟʠʡʢʣʤʥʦʧʨʩʪʫʬʭʮʯ"
     },
    {"name": "data-enrichment-latin1-greek",
     "splunk_hec_json_event_enrichment": "test=greek,chars=ͰͱͲͳʹ͵Ͷͷ͸͹ͺͻͼͽ;Ϳ΀΁΂΃΄΅Ά·ΈΉΊ΋Ό΍ΎΏΐΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡ΢ΣΤΥΦΧΨΩΪΫάέήίΰαβγδεζηθικλμνξοπρςστυφχψωϊϋόύώϏϐϑϒϓϔϕϖϗϘϙϚϛϜϝϞϟϠϡϢϣϤϥϦϧϨϩϪϫϬϭϮϯϰϱϲϳϴϵ϶ϷϸϹϺϻϼϽϾϿ"
     },
    {"name": "data-enrichment-latin1-diacriticalMarks",
     "splunk_hec_json_event_enrichment": "test=diacriticalMarks,chars=	́	̂	̃	̄	̅	̆	̇	̈	̉	̊	̋	̌	̍	̎	̏	̐	̑	̒	̓	̔	̕	̖	̗	̘	̙	̚	̛	̜	̝	̞	̟	̠	̡	̢	̣	̤	̥	̦	̧	̨	̩	̪	̫	̬	̭	̮	̯	̰	̱	̲	̳	̴	̵	̶	̷	̸	̹	̺	̻	̼	̽	̾	̿	̀	́	͂	̓	̈́	ͅ	͆	͇	͈	͉	͊	͋	͌	͍	͎	͏	͐	͑	͒	͓	͔	͕	͖	͗	͘	͙	͚	͛	͜	͝	͞	͟	͠	͡	͢	ͣ	ͤ	ͥ	ͦ	ͧ	ͨ	ͩ	ͪ	ͫ	ͬ	ͭ	ͮ	ͯ"
     },
    {"name": "data-onboarding-event-endpoint-no-ack",
     "splunk_hec_raw": False,
     "splunk_hec_ack_enabled": "false",
     "splunk_hec_json_event_enrichment": "chars=data-onboarding-event-endpoint-no-ack"
     },
    {"name": "data-onboarding-raw-endpoint-ack",
     "splunk_hec_raw": True,
     "splunk_hec_ack_enabled": "true",
     "splunk_hec_token": config["splunk_token_ack"],
     "splunk_sourcetypes": "raw_data-ack"
     },
    {"name": "data-onboarding-event-endpoint-ack",
     "splunk_hec_raw": False,
     "splunk_hec_ack_enabled": "true",
     "splunk_hec_token": config["splunk_token_ack"],
     "splunk_hec_json_event_enrichment": "chars=data-onboarding-event-endpoint-ack"
     },
    {"name": "data-onboarding-raw-endpoint-no-ack",
     "splunk_hec_raw": True,
     "splunk_hec_ack_enabled": "false",
     "splunk_sourcetypes": "raw_data-no-ack"
     },
    {"name": "line_breaking_of_raw_data",
     "splunk_sources": "kafka:topic_test_break_raw",
     "splunk_hec_raw": True,
     "splunk_hec_raw_line_breaker": "######"},
    {"name": "line_breaking_of_event_data",
     "splunk_sources": "kafka:topic_test_break_event",
     "splunk_hec_raw": False,
     "splunk_hec_raw_line_breaker": "######"},
    {"name": "test_tasks_max_1_hec_raw_false",
     "tasks_max": "1",
     "splunk_hec_raw": False,
     "splunk_hec_json_event_enrichment": "chars=test_tasks_max_1_hec_raw_false"},
    {"name": "test_tasks_max_1_hec_raw_true",
     "tasks_max": "1",
     "splunk_hec_raw": True,
     "splunk_sourcetypes": "raw_data-tasks_max-1"},
    {"name": "test_tasks_max_3_hec_raw_true",
     "tasks_max": "3",
     "splunk_hec_raw": True,
     "splunk_sourcetypes": "raw_data-tasks_max_3"
     },
    {"name": "test_tasks_max_3_hec_raw_false",
     "tasks_max": "3",
     "splunk_hec_raw": False,
     "splunk_hec_json_event_enrichment": "chars=test_tasks_max_3_hec_raw_false"},
    {"name": "test_tasks_max_null",
     "tasks_max": "null",
     "splunk_hec_raw": False,
     "splunk_hec_json_event_enrichment": "chars=test_tasks_max_null"},
    {"name": "test_1_source_hec_raw_true",
     "splunk_hec_raw": True,
     "splunk_sources": "test_1_source_hec_raw_true"},
    {"name": "test_1_source_hec_raw_false",
     "splunk_hec_raw": False,
     "splunk_sources": "test_1_source_hec_raw_false",
     "splunk_hec_json_event_enrichment": "chars=test_1_source_hec_raw_false"},
    {"name": "test_2_sources_hec_raw_true",
     "splunk_hec_raw": True,
     "topics": config["kafka_topic"] + "," + config["kafka_topic_2"],
     "splunk_sources": "source_1_raw,source_2_raw"},
    {"name": "test_2_source_hec_raw_false",
     "splunk_hec_raw": False,
     "topics": config["kafka_topic"] + "," + config["kafka_topic_2"],
     "splunk_sources": "source_1_event,source_2_event",
     "splunk_hec_json_event_enrichment": "chars=test_2_source_hec_raw_false"},
    {"name": "test_1_sourcetype_hec_raw_true",
     "splunk_hec_raw": True,
     "splunk_sourcetypes": "test_1_sourcetype_hec_raw_true"},
    {"name": "test_1_sourcetype_hec_raw_false",
     "splunk_hec_raw": False,
     "splunk_sourcetypes": "test_1_sourcetype_hec_raw_false",
     "splunk_hec_json_event_enrichment": "chars=test_1_sourcetype_hec_raw_false"},
    {"name": "test_2_sourcetype_hec_raw_true",
     "splunk_hec_raw": True,
     "topics": config["kafka_topic"] + "," + config["kafka_topic_2"],
     "splunk_sourcetypes": "sourcetype_1_raw,sourcetype_2_raw"},
    {"name": "test_2_sourcetype_hec_raw_false",
     "splunk_hec_raw": False,
     "topics": config["kafka_topic"] + "," + config["kafka_topic_2"],
     "splunk_sourcetypes": "sourcetype_1_event,sourcetype_2_event",
     "splunk_hec_json_event_enrichment": "chars=test_2_sourcetype_hec_raw_false"},
    # {"name": "ssl_validate_certs_true",
    #  "splunk_hec_ssl_validate_certs": "true",
    #  "splunk_hec_ssl_trust_store_path": "/tmp/keystore.jks",
    #  "splunk_hec_ssl_trust_store_password": "notchangeme",
    #  "splunk_sources": "ssl_validate_certs_true"},
    {"name": "test_header_support_false_event",
     "splunk_header_support": "false",
     "splunk_hec_raw": False,
     "topics": config["kafka_header_topic"],
     "splunk_sources": "test_header_support_false_event"},
    {"name": "test_header_support_false_raw",
     "splunk_header_support": "false",
     "splunk_hec_raw": True,
     "topics": config["kafka_header_topic"],
     "splunk_sources": "test_header_support_false_raw"},
    {"name": "test_header_support_true_event",
     "splunk_header_support": "true",
     "splunk_hec_raw": False,
     "topics": config["kafka_header_topic"],
     "splunk_header_index": "header_index",
     "splunk_header_host": "header_host_event",
     "splunk_header_source": "header_source_event",
     "splunk_header_sourcetype": "header_sourcetype_event"},
    {"name": "test_header_support_true_raw",
     "splunk_header_support": "true",
     "splunk_hec_raw": True,
     "topics": config["kafka_header_topic"],
     "splunk_header_index": "header_index",
     "splunk_header_host": "header_host_raw",
     "splunk_header_source": "header_source_raw",
     "splunk_header_sourcetype": "header_sourcetype_raw"},
    {"name": "test_header_support_true_custom_event",
     "splunk_header_support": "true",
     "splunk_hec_raw": False,
     "topics": config["kafka_header_topic"],
     "splunk_header_custom": "splunk.header.index,splunk.header.host,splunk.header.source",
     "splunk_sourcetypes": "test_header_support_true_custom_event",
     "splunk_hec_json_event_enrichment": "chars=test_header_support_true_custom_event"},
    {"name": "test_header_support_true_custom_raw",
     "splunk_header_support": "true",
     "splunk_hec_raw": True,
     "topics": config["kafka_header_topic"],
     "splunk_header_custom": "splunk.header.index,splunk.header.host,splunk.header.sourcetype",
     "splunk_sources": "test_header_support_true_custom_raw"},
    {"name": "test_splunk_hec_json_event_formatted_true_event_data",
     "splunk_hec_raw": False,
     "splunk_hec_json_event_formatted": "true",
     "splunk_hec_json_event_enrichment": "chars=test_splunk_hec_json_event_formatted_true_event_data"},
    {"name": "test_splunk_hec_json_event_formatted_false_event_data",
     "splunk_hec_raw": False,
     "splunk_hec_json_event_formatted": "false",
     "splunk_hec_json_event_enrichment": "chars=test_splunk_hec_json_event_formatted_false_event_data"},
    {"name": "test_splunk_hec_json_event_formatted_true_raw_data",
     "splunk_hec_raw": True,
     "splunk_hec_json_event_formatted": "true",
     "splunk_sourcetypes": "test_splunk_hec_json_event_formatted_true_raw_data"},
    {"name": "test_splunk_hec_json_event_formatted_false_raw_data",
     "splunk_hec_raw": True,
     "splunk_hec_json_event_formatted": "false",
     "splunk_sourcetypes": "test_splunk_hec_json_event_formatted_false_raw_data"},
    {"name": "test_empty_hec_token",
     "splunk_hec_token": None,
     "splunk_hec_json_event_enrichment": "chars=test_empty_hec_token"},
    {"name": "test_incorrect_hec_token",
     "splunk_hec_token": "dummy-tocken",
     "splunk_hec_json_event_enrichment": "chars=test_incorrect_hec_token"},
    {"name": "test_splunk_hec_empty_event",
     "topics": "test_splunk_hec_malformed_events",
     "splunk_hec_raw": False,
     "splunk_hec_json_event_enrichment": "chars=hec_empty_events_{}".format(config['timestamp'])},
    {"name": "test_splunk_hec_malformed_events",
     "topics": "test_splunk_hec_malformed_events",
     "splunk_hec_raw": False,
     "splunk_hec_json_event_enrichment": "chars=hec_malformed_events_{}".format(config['timestamp'])}
]
